package Transport.Interfaces.SpecialPurposeVehicles.InterdepartmentalTransport;

import Transport.Interfaces.SpecialPurposeVehicles.SpecialPurposeVehicles;

public interface InterdepartmentalTransport extends SpecialPurposeVehicles {
}
